{
  "comments": [
    {
      "key": {
        "uuid": "5f893cc4_1b569e96",
        "filename": "common/utils.cpp",
        "patchSetId": 4
      },
      "lineNbr": 536,
      "author": {
        "id": 1000845
      },
      "writtenOn": "2021-08-31T16:03:12Z",
      "side": 1,
      "message": "are we trying to snub the exception? would we want to throw an error message?",
      "revId": "2b6be5bf4334a1d582029241ae74992419283903",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "9fbb77ea_16207d9a",
        "filename": "common/utils.hpp",
        "patchSetId": 4
      },
      "lineNbr": 365,
      "author": {
        "id": 1000845
      },
      "writtenOn": "2021-08-31T16:03:12Z",
      "side": 1,
      "message": "new line",
      "revId": "2b6be5bf4334a1d582029241ae74992419283903",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}