{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "0559537a_0b8e5db1",
        "filename": "pldmd/dbus_impl_requester.hpp",
        "patchSetId": 12
      },
      "lineNbr": 52,
      "author": {
        "id": 1001384
      },
      "writtenOn": "2023-05-08T20:16:16Z",
      "side": 1,
      "message": "next function throws two different types of exceptions\nstd::runtime_error (https://gerrit.openbmc.org/c/openbmc/pldm/+/62580/12/pldmd/instance_id.hpp#54)\nstd::system_category().default_error_condition (https://gerrit.openbmc.org/c/openbmc/pldm/+/62580/12/pldmd/instance_id.hpp#59)\n\nNeed to catch those exceptions use catch{} and handle properly.\n\nOr do you expect the caller of getInstanceIs to catch the exceptions?",
      "revId": "88ffaebe04e67b5dcd0cd3f25049bc66bef7591e",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "a5aab128_cb1072cd",
        "filename": "pldmd/dbus_impl_requester.hpp",
        "patchSetId": 12
      },
      "lineNbr": 53,
      "author": {
        "id": 1001384
      },
      "writtenOn": "2023-05-08T20:16:16Z",
      "side": 1,
      "message": "We will never enter this path where rc is set to -EAGAIN. This condition should be covered under catch.",
      "revId": "88ffaebe04e67b5dcd0cd3f25049bc66bef7591e",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}