{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "a6bcea40_a827396c",
        "filename": "fw-update/inventory_manager.cpp",
        "patchSetId": 3
      },
      "lineNbr": 22,
      "author": {
        "id": 1001384
      },
      "writtenOn": "2023-05-08T20:21:04Z",
      "side": 1,
      "message": "is it required to catch the exception thrown by next()?",
      "revId": "aceb12299874ea156c4830d1cb183a4e649f7561",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}